#!/usr/bin/env node
/**
 * Codegen script: Read Prisma schema → Generate TypeScript enum definitions.
 * Source of truth: apps/backend/prisma/schema.prisma
 * Output: packages/shared-types/src/generated/enums.ts
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PRISMA_SCHEMA = resolve(__dirname, '../../../apps/backend/prisma/schema.prisma');
const OUTPUT_DIR = resolve(__dirname, '../src/generated');
const OUTPUT_FILE = resolve(OUTPUT_DIR, 'enums.ts');

// Read Prisma schema
const schema = readFileSync(PRISMA_SCHEMA, 'utf-8');

// Extract enum blocks: "enum Name { ... }"
const enumRegex = /enum\s+(\w+)\s*\{([^}]+)\}/g;
const enums = [];

const allMatches = [...schema.matchAll(enumRegex)];
for (const match of allMatches) {
  const name = match[1];
  const body = match[2];
  const values = body
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('//'))
    .map((line) => line.replace(/\/\/.*$/, '').trim()) // strip inline comments
    .filter(Boolean);

  if (values.length > 0) {
    enums.push({ name, values });
  }
}

if (enums.length === 0) {
  console.error('No enums found in Prisma schema');
  process.exit(1);
}

// Generate TypeScript
const lines = [
  '// ------------------------------------------------------------------',
  '// AUTO-GENERATED by packages/shared-types/scripts/generate-enums.mjs',
  '// DO NOT EDIT MANUALLY — edit apps/backend/prisma/schema.prisma instead.',
  '// ------------------------------------------------------------------',
  '',
];

for (const { name, values } of enums) {
  lines.push(`export enum ${name} {`);
  for (const value of values) {
    // Prisma enum values are lowercase, use UPPER_CASE for TS enum members
    const member = value.toUpperCase();
    lines.push(`  ${member} = '${value}',`);
  }
  lines.push('}');
  lines.push('');
}

// Write output
mkdirSync(OUTPUT_DIR, { recursive: true });
writeFileSync(OUTPUT_FILE, lines.join('\n'), 'utf-8');

console.log(`✓ Generated ${enums.length} enums → ${OUTPUT_FILE}`);
